#!/usr/bin/env python3

"""
Generate miscellaneous TLS test cases relating to the handshake.
"""

# Copyright The Mbed TLS Contributors
# SPDX-License-Identifier: Apache-2.0 OR GPL-2.0-or-later

import argparse
import sys
from typing import Optional

from mbedtls_framework import tls_test_case
from mbedtls_framework import typing_util
def write_handshake_tests(out: typing_util.Writable) -> None:
    """Generate handshake tests."""
    out.write(f"""\
# Miscellaneous tests related to the TLS handshake layer.
#
# Automatically generated by {sys.argv[0]}. Do not edit!

# Copyright The Mbed TLS Contributors
# SPDX-License-Identifier: Apache-2.0 OR GPL-2.0-or-later

""")
    out.write("""\
# End of automatically generated file.
""")

def main() -> None:
    """Command line entry point."""
    parser = argparse.ArgumentParser()
    parser.add_argument('-o', '--output',
                        default='tests/opt-testcases/handshake-generated.sh',
                        help='Output file')
    args = parser.parse_args()
    with open(args.output, 'w') as out:
        write_handshake_tests(out)

if __name__ == '__main__':
    main()
