"""Generate C preprocessor code to check for bad configurations.
"""

## Copyright The Mbed TLS Contributors
## SPDX-License-Identifier: Apache-2.0 OR GPL-2.0-or-later

import argparse
import os
import sys
import typing
from typing import Dict

from . import build_tree
from . import typing_util


class BranchData(typing.NamedTuple):
    """The relevant aspects of the configuration on a branch."""

    # Subdirectory where the generated headers will be located.
    header_directory: str

    # Prefix used to the generated headers' basename.
    header_prefix: str

    # Prefix used for C preprocessor macros.
    project_cpp_prefix: str

    # removed_options[option_name] = replacement_description
    # replacement_description is a short string intended for human consumption.
    removed_options: Dict[str, str]


class HeaderGenerator:
    """Common code for BeforeHeaderGenerator and AfterHeaderGenerator."""

    def __init__(self, branch_data) -> None:
        self.branch_data = branch_data
        self.prefix = branch_data.project_cpp_prefix + '_CONFIG_CHECK_'
        self.remember_defined_prefix = self.prefix + 'defined_'
        self.dead_option_macro = self.prefix + 'option_is_no_longer_supported'
        self.allow_removed = self.prefix + 'ALLOW_REMOVED_OPTIONS'

    def write_stanza(self, out: typing_util.Writable, option: str) -> None:
        """Write the part of the output corresponding to one config option."""
        raise NotImplementedError

    def write_content(self, out: typing_util.Writable) -> None:
        """Write the output for all config options to be processed."""
        for option in sorted(self.branch_data.removed_options.keys()):
            self.write_stanza(out, option)

    def write(self, filename: str) -> None:
        """Write the whole output file."""
        with open(filename, 'w') as out:
            out.write(f"""\
/* {os.path.basename(filename)}: checks before including the user configuration file. */
/* Automatically generated by {os.path.basename(sys.argv[0])}. Do not edit! */

#if !defined({self.allow_removed})

#define {self.dead_option_macro} 0xdeadc0f1

/* *INDENT-OFF* */
""")
            self.write_content(out)
            out.write(f"""
/* *INDENT-ON* */

#endif /* !defined({self.allow_removed}) */

/* End of automatically generated {os.path.basename(filename)} */
""")


class BeforeHeaderGenerator(HeaderGenerator):
    """Generate a header to include immediately before the user configuration."""

    def write_stanza(self, out: typing_util.Writable, option: str) -> None:
        was_defined = self.remember_defined_prefix + option
        out.write(f"""
#if defined({option})
#  define {was_defined} 1
#  undef {option}
#else
#  define {was_defined} 0
#endif
#define {option} {self.dead_option_macro}
""")


class AfterHeaderGenerator(HeaderGenerator):
    """Generate a header to include immediately after the user configuration."""

    def write_stanza(self, out: typing_util.Writable, option: str) -> None:
        was_defined = self.remember_defined_prefix + option
        suggestion = self.branch_data.removed_options[option]
        out.write(f"""
#if !defined({option})
#  error "Undefining {option} is no longer supported. Suggestion: {suggestion}"
#elif ({option} + 0) != {self.dead_option_macro}
#  error "Defining {option} is no longer supported. Suggestion: {suggestion}"
#endif
#undef {option}
#if {was_defined}
#  define {option}
#endif
#undef {was_defined}
""")


def generate_header_files(root: str, branch_data: BranchData) -> None:
    """Generate the header files to include before and after *config.h."""
    before_generator = BeforeHeaderGenerator(branch_data)
    before_generator.write(os.path.join(root,
                                        branch_data.header_directory,
                                        branch_data.header_prefix +
                                        'config_check_before.h'))
    after_generator = AfterHeaderGenerator(branch_data)
    after_generator.write(os.path.join(root,
                                       branch_data.header_directory,
                                       branch_data.header_prefix +
                                       'config_check_after.h'))


def main(branch_data: BranchData) -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    _options = parser.parse_args()
    root = build_tree.guess_project_root()
    generate_header_files(root, branch_data)
