"""Test the configuration checks generated by generate_config_checks.py.
"""

## Copyright The Mbed TLS Contributors
## SPDX-License-Identifier: Apache-2.0 OR GPL-2.0-or-later

import os
import subprocess
import sys
import unittest
from typing import List, Optional, Pattern, Union


class TestConfigChecks(unittest.TestCase):
    """Unit tests for checks generated by config_checks_generator."""

    def user_config_file_name(self, variant: str) -> str:
        """Construct a unique temporary file name for a user config header."""
        name = os.path.splitext(os.path.basename(sys.argv[0]))[0]
        pid = str(os.getpid())
        oid = str(id(self))
        return f'tmp-user_config_{variant}-{name}-{pid}-{oid}.h'

    def write_user_config(self, variant: str, content: Optional[str]) -> Optional[str]:
        """Write a user configuration file with the given content.

        If content is None, ensure the file does not exist.

        Return None if content is none, otherwise return the file name.
        """
        file_name = self.user_config_file_name(variant)
        if content is None:
            if os.path.exists(file_name):
                os.remove(file_name)
            return None
        if content and not content.endswith('\n'):
            content += '\n'
        with open(file_name, 'w', encoding='ascii') as out:
            out.write(content)
        return file_name

    @staticmethod
    def run_with_config_files(crypto_user_config_file: Optional[str],
                              mbedtls_user_config_file: Optional[str],
                              extra_options: List[str],
                              is_mbedtls: bool,
                              ) -> subprocess.CompletedProcess:
        """Run cpp with the given user configuration files.

        Return the CompletedProcess object capturing the return code,
        stdout and stderr.
        """
        cmd = ['cpp']
        if crypto_user_config_file is not None:
            cmd.append(f'-DTF_PSA_CRYPTO_USER_CONFIG_FILE="{crypto_user_config_file}"')
        if mbedtls_user_config_file is not None:
            cmd.append(f'-DMBEDTLS_USER_CONFIG_FILE="{mbedtls_user_config_file}"')
        for directory in [
                'drivers/builtin/include',
                'include',
        ]:
            cmd.append('-I' + directory)
            cmd.append('-Itf-psa-crypto/' + directory)
        cmd.append('-I.')
        cmd += extra_options
        cpp_input = '#include <tf-psa-crypto/build_info.h>\n'
        if is_mbedtls:
            cpp_input += '#include <mbedtls/build_info.h>\n'
        return subprocess.run(cmd,
                              check=False,
                              encoding='ascii',
                              input=cpp_input,
                              stdout=subprocess.PIPE,
                              stderr=subprocess.PIPE)

    def run_with_config(self,
                        crypto_user_config: Optional[str],
                        mbedtls_user_config: Optional[str] = None,
                        extra_options: Optional[List[str]] = None,
                        ) -> subprocess.CompletedProcess:
        """Run cpp with the given content for user configuration files.

        Return the CompletedProcess object capturing the return code,
        stdout and stderr.
        """
        if extra_options is None:
            extra_options = []
        crypto_user_config_file = None
        mbedtls_user_config_file = None
        try:
            crypto_user_config_file = \
                self.write_user_config('crypto', crypto_user_config)
            mbedtls_user_config_file = \
                self.write_user_config('mbedtls', mbedtls_user_config)
            cp = self.run_with_config_files(crypto_user_config_file,
                                            mbedtls_user_config_file,
                                            extra_options,
                                            mbedtls_user_config is not None)
            return cp
        finally:
            if crypto_user_config_file is not None and \
               os.path.exists(crypto_user_config_file):
                os.remove(crypto_user_config_file)
            if mbedtls_user_config_file is not None and \
               os.path.exists(mbedtls_user_config_file):
                os.remove(mbedtls_user_config_file)

    def good_case(self,
                  crypto_user_config: Optional[str],
                  mbedtls_user_config: Optional[str] = None,
                  extra_options: Optional[List[str]] = None,
                  ) -> None:
        """Run cpp with the given user config(s). Expect no error.

        Pass extra_options on the command line of cpp.
        """
        cp = self.run_with_config(crypto_user_config, mbedtls_user_config,
                                  extra_options=extra_options)
        self.assertEqual(cp.stderr, '')
        self.assertEqual(cp.returncode, 0)

    def bad_case(self,
                 crypto_user_config: Optional[str],
                 mbedtls_user_config: Optional[str] = None,
                 error: Optional[Union[str, Pattern]] = None,
                 extra_options: Optional[List[str]] = None,
                 ) -> None:
        """Run cpp with the given user config(s). Expect errors.

        Pass extra_options on the command line of cpp.

        If error is given, the standard error from cpp must match this regex.
        """
        cp = self.run_with_config(crypto_user_config, mbedtls_user_config,
                                  extra_options=extra_options)
        if error is not None:
            self.assertRegex(cp.stderr, error)
        self.assertGreater(cp.returncode, 0)
        self.assertLess(cp.returncode, 126)

    def test_nominal(self) -> None:
        self.good_case(None)
